edit job 7

diff --git a/.github/workflows/retraining_pipeline.yml b/.github/workflows/retraining_pipeline.yml
--- a/.github/workflows/retraining_pipeline.yml
+++ b/.github/workflows/retraining_pipeline.yml
@@ -54,9 +54,12 @@ jobs:
         run: |
           EXP_ID=$(mlflow experiments search | grep "Automated CI Training" | awk '{print $1}')
           RUN_ID=$(mlflow runs list --experiment-id $EXP_ID | grep -v 'RUN_ID' | head -n 1 | awk '{print $1}')
+          if [ -z "$RUN_ID" ]; then
+          echo "Error: RUN_ID is empty. Did the training step fail?"
+          exit 1
+          fi
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           echo "Discovered Run ID: $RUN_ID"
-        
 
       - name: 8. Commit MLflow Artifacts to Repo
         uses: stefanzweifel/git-auto-commit-action@v5
