update

diff --git a/.github/workflows/retraining_pipeline.yml b/.github/workflows/retraining_pipeline.yml
--- a/.github/workflows/retraining_pipeline.yml
+++ b/.github/workflows/retraining_pipeline.yml
@@ -52,14 +52,16 @@ jobs:
         shell: bash -l {0}
         working-directory: ./MLProject
         run: |
-          EXP_ID=$(mlflow experiments search | grep "Automated CI Training" | awk '{print $1}')
-          RUN_ID=$(mlflow runs list --experiment-id $EXP_ID | grep -v 'RUN_ID' | head -n 1 | awk '{print $1}')
-          if [ -z "$RUN_ID" ]; then
-          echo "Error: RUN_ID is empty. Did the training step fail?"
-          exit 1
+          EXP_ID=$(mlflow experiments search | awk -F ' +' '$0 ~ /Automated CI Training/ {print $1}')
+          RUN_ID=$(mlflow runs list --experiment-id $EXP_ID --order-by start_time desc | awk 'NR==2 {print $1}')
+            
+          if [[ -z "$RUN_ID" || "$RUN_ID" == "Date" ]]; then
+            echo "Error: Invalid RUN_ID: $RUN_ID"
+            exit 1
           fi
-          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
+        
           echo "Discovered Run ID: $RUN_ID"
+          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
 
       - name: 8. Commit MLflow Artifacts to Repo
         uses: stefanzweifel/git-auto-commit-action@v5
